language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install numpy
  - pip install pandas
# command to run tests
script: 
  - python micronorm -m RLE data/read_count.csv
  - python micronorm -m CLR data/read_count.csv
